//
//  NewChatLoginInteractor.swift
//  MFSMobile
//
//  Created by 戴元平 on 9/1/19.
//  Copyright (c) 2019 David. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewChatLoginBusinessLogic
{
  func doSomething(request: NewChatLogin.Something.Request)
}

protocol NewChatLoginDataStore
{
  //var name: String { get set }
}

class NewChatLoginInteractor: NewChatLoginBusinessLogic, NewChatLoginDataStore
{
  var presenter: NewChatLoginPresentationLogic?
  var worker: NewChatLoginWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NewChatLogin.Something.Request)
  {
    worker = NewChatLoginWorker()
    worker?.doSomeWork()
    
    let response = NewChatLogin.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
