//
//  NewChatLoginPresenter.swift
//  MFSMobile
//
//  Created by 戴元平 on 9/1/19.
//  Copyright (c) 2019 David. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewChatLoginPresentationLogic
{
  func presentSomething(response: NewChatLogin.Something.Response)
}

class NewChatLoginPresenter: NewChatLoginPresentationLogic
{
  weak var viewController: NewChatLoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NewChatLogin.Something.Response)
  {
    let viewModel = NewChatLogin.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
